### ISSUE TITLE
Minsk crashes with a single BadToken being passed as an input

### ISSUE THREAD

**Issue by d-dizhevsky** [terrajobst/minsk#12]
![image](https://user-images.githubusercontent.com/25821724/47708818-98d1d300-dc37-11e8-9e01-9754eefdb222.png)

AOR exception occurs here: https://github.com/terrajobst/minsk/blob/5031b6d633e78435491a69efe01878bd28cdc3b5/Minsk/CodeAnalysis/Syntax/Lexer.cs#L131

**Comment by terrajobst** [comment]
Thanks for the bug report. I'll fix it live on stream next week!

**Comment by terrajobst** [comment]
Thanks for the bug report. I'll fix it live on stream next week.
