### ISSUE TITLE
Minsk crashes with AOR exception when there is no closing parenthesis 

### ISSUE THREAD

**Issue by d-dizhevsky** [terrajobst/minsk#13]
```
a = (1 + (2 * 2) - (1 - 1)
```

The diagnostics message seems to be correct, but IMO it should not crash 

![image](https://user-images.githubusercontent.com/25821724/47709747-ab4d0c00-dc39-11e8-9755-c4f69cd440c9.png)

**Comment by terrajobst** [comment]
Thanks for the bug report. I'll fix it live on stream next week.
