### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by blaumeise20** [terrajobst/minsk#175]
Is this project dead? It seems like it is not going to be continued, because there are no interactions with it. I would personally think that it is a good idea to continue with it, but I don't know what you (@terrajobst) want to do.

**Comment by Aniel** [comment]
On a recent YouTube video there was some hint that the project will continue soon :)

https://www.youtube.com/watch?v=0mFTOpHkQYw

![image](https://user-images.githubusercontent.com/4410553/122753163-1f78ca00-d292-11eb-8041-530d6f63b5c5.png)

**Comment by terrajobst** [comment]
![](https://media2.giphy.com/media/A3dD2XWfJ7tV6/giphy.gif)

**Comment by blaumeise20** [comment]
Weird. The confirmation has been 3 months ago and nothing happened.

**Comment by blaumeise20** [comment]
Still nothing after more than 2 years?
