### ISSUE TITLE
Using this project and videos as inspiration to create one in JS.

### ISSUE THREAD

**Issue by fenilli** [terrajobst/minsk#186]
I wanted to know @terrajobst if its fine to use this project and the youtube videos as base and inspiration to make a JS one using the ideas from these videos?

The project is here: https://github.com/fenilli/clad-lang

And the README properly gives credit to this repository and videos.

**Comment by terrajobst** [comment]
Absolutely! I started this project to inspire more people to toy with compilers and lower the barrier of entry for educational content.

Consider doing viedoes about your content too! I'm happy amplify whatever you come up with on social media :-)
