### ISSUE TITLE
I want to repost your video

### ISSUE THREAD

**Issue by forestbat** [terrajobst/minsk#52]
Hello dear Immo，I'm a Chinese Video Maker，I'm interested in your videos such as "making a compiler" and so on，can I post it to other websites such as [bilibili](https://www.bilibili.com/)？I will tell other people the origin author is you and put origin link under these videos。
Hope your reply.

**Comment by terrajobst** [comment]
Hey @forestbat, thanks for reaching out. As long as you give credit that seems fine to me. Happy coding!
