### ISSUE TITLE
Still interested!

### ISSUE THREAD

**Issue by LunicLynx** [terrajobst/minsk#77]
Hi Immo,

just wanted to let you know that there are some people still interested in a continuation of this series. 

Thanks,
Flo

**Comment by CronosTs** [comment]
October, almost november and I'm istill interested. Please, continue with the series.

**Comment by RogueMacro** [comment]
Yeah, would love to see more episodes pop up!

**Comment by Aniel** [comment]
@terrajobst any update regarding a continuation of the series this year?
This series is really interesting and helpful.

**Comment by hamsbrar** [comment]
@terrajobst your whole series is superb, and especially you, I'm missing a lot, you can try something uploading videos on something else if you have some time. I hope you are alright.

**Comment by Aniel** [comment]
Heads up for all folks that don't monitor twitter ;)

The series will continue today (8 AM PST ~ 9h from now)  
https://www.youtube.com/watch?v=F0ZeU0aSkfQ&list=PLRAdsfhKI4OWNOSfS7EUu5GRAVmze1t2y

**Comment by LunicLynx** [comment]
He is back!
