### ISSUE TITLE
Parsing and syntax for dot accessor!

### ISSUE THREAD

**Issue by xDGameStudios** [terrajobst/minsk#78]
I'm writting here so I can reach you @terrajobst and all the interested people following this channel.
I'm trying to add . (dot) accessor in a programming language I'm trying to build.. I wanted to know what would be the best approach for it...

should I use the BinaryExpressionSyntax class and treat . (dot) as an operator?
or should I build a class specially for this... ie: DotAccessorExpressionSyntax
what kind of information should I keep there?

**Comment by LunicLynx** [comment]
Hi @xDGameStudios,

The dot accessor is at first a binary expression und bound it is a Member Access expression, at least from a c# like point of view.

To make it obvious just think about how the dot behaves when you use it in other expressions.

„3“ + 5.ToString()

(3 + 5).ToString()

**Comment by xDGameStudios** [comment]
Thank you @LunicLynx  that was helpful ;) And I will take that into consideration! :)
